### PR TITLE
made a couple of changes on README file

### PR DESCRIPTION
**Pull request by kitwi**
Added a slash art I made and changed a few things on the README text (the book in the splash art can be used as an icon for the program). I'm also interest in translating the program to Brazilian Portuguese if necessary.

### CODE REVIEW

**Comment by AhmedSherifH** [comment]
Thank you! I'll be sure to include the icon in the next commit. As for translations, I feel the program doesn't have a lot of text to require translation, but I'm definitely down to try.

**Comment by kitwi** [comment]
for some reason i wasn't able to run the program, so I didn't check the UI design yet, gonna try again soon.

**Comment by AhmedSherifH** [comment]
Feel free to let me know if you need help with anything.

**Comment by kitwi** [comment]
i just realized i didnt had the requests_html module installed, I downloaded it and everything works fine now

**Pull request merged**
